#!/bin/csh -f
set n = $1
set idx = 4
set player = $2
shift
shift

while ( $idx >= 0 )
	@ x = $n + ( 5 * $idx )

	if ( $argv[$x] == '_' ) then
		set argv[$x] = $player
		break
	endif
	@ idx --
end

echo $argv
exit ( $idx < 0 )
